export class Constants {
  static readonly API_KEY = "f13f118b8329b552f3f120d22ce3ebfc"
  static readonly WEB_KEY = "84e49e1443d373e3ea7526309a7dea77"
  /**
   * 高德基地址
   */
  static readonly BASE_URL = "https://restapi.amap.com/"
  /**
   * 输入提示url
   */
  static readonly INPUT_TIPS_URL = "v3/assistant/inputtips"
  /**
   * 路径规划
   */
  static readonly ROUTE_PLAN_URl = "v3/direction/"

  /**
   * 步行
   */
  static readonly PLAN_WALKING = 'walking';

  /**
   * 公交
   */
  static readonly PLAN_TRANS ="transit/integrated"

  /**
   * 骑行
   */
  static readonly PLAN_BICYCLING = "bicycling"
}